---
title: "doc_aging_plots"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(councildown)
library(dplyr)
```

```{r}

year_age_fr <- read.csv("../data/input/raw/state_year_age_fr.csv")
year_age_tr_return <- read.csv("..//data/input/raw/state_year_age_tr_returns.csv")
```

```{r}
returns_only <- subset(year_age_tr_return,cohort == "total_return")
```

```{r}

p <- ggplot(data=returns_only) + 
  geom_line(aes(x=year, y=num_50_over, colour="50 & Over"),
            size=1), linetype = "dashed") +
  geom_line(aes(x=year, y=(age16_18+age19_20), 
                colour="20 & Under")) +
  geom_line(aes(x=year, y=(age21_24+age25_29), 
                colour="21-29")) +
  geom_line(aes(x=year, y=(age30_34), 
                colour="30-34")) +
  geom_line(aes(x=year, y=(age35_39), 
                colour="35-39")) +
  geom_line(aes(x=year, y=(age40_44+age45_49), 
                colour="40-49")) +
  scale_x_continuous(n.breaks=9) + labs(title="NYS Returns within Three years Post (2011-2021)", 
                                        subtitle="Reported by the DOCCS Annual Inmate Releases report.",
                                        x="Year Released",
                                        y="Number of Individuals Returned",
                                        color="Age Group") + theme_nycc() +
   scale_color_nycc("mixed")

ggsave(p, filename = "../visuals/returns_age_num.png", width = 8, height = 5)
```

```{r}
#prop out of total # inmates returned that year
p <- ggplot(data=returns_only) + 
  geom_line(aes(x=year, y=num_50_over/year_total, colour="50 & Over"),
            linetype = "dashed", size =1) +
  geom_line(aes(x=year, y=(age16_18+age19_20)/year_total, colour="20 & under")) +
  geom_line(aes(x=year, y=(age21_24+age25_29)/year_total, colour="21-29")) +
  geom_line(aes(x=year, y=(age30_34+age35_39)/year_total, colour="30-34")) +

  geom_line(aes(x=year, y=(age40_44+age45_49)/year_total, colour="40-49")) +
  scale_x_continuous(n.breaks=9) + scale_y_continuous(labels=scales::percent) +labs(title="NYS Returns within Three Years Post-Release (2011-2021)", 
                                        subtitle="Reported by the DOCCS Annual Inmate Releases report.",
                                        x="Year Released",
                                        y="Percent of Individuals Returned",
                                        color="Age Group") + 
  theme_nycc() + scale_color_nycc()
p
ggsave(p, filename = "../visuals/returns_age_prop.png", width = 8, height = 5)
```

```{r, include=FALSE}
ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_released)) + scale_x_continuous(n.breaks=9) +
  geom_line(aes(x=year, y=total_50_over)) +
  theme_nycc()
```

```{r, include=FALSE}
ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_50_over/total_released)) + scale_x_continuous(n.breaks=9) +
  theme_nycc()
```

```{r}
# ----- AGE OF PEOPLE RELEASED FROM DOC FACILITIES OVER TIME -----
# --- OF AGING INDIVIDUALS ---
# These were individuals who were released to the community for the first time on their current sentence due to release by the Board of Parole, release due to reaching their approved conditional release date (including maximum expiration with post-release supervision), or release based on reaching maximum expiration of sentence.
ggplot(data=year_age_fr) + 
  geom_line(aes(x=year, y=total_50_over, colour="all ages 50+")) +
  geom_line(aes(x=year, y=age50_59, colour="50-59")) +
  geom_line(aes(x=year, y=age60_64, colour="60-64")) +
  geom_line(aes(x=year, y=age65_69, colour="65-69")) +
  geom_line(aes(x=year, y=age_70over, colour="70+")) + 
  scale_x_continuous(n.breaks=9) + labs(title="NYS First Releases (2011-2020)", 
                                        subtitle="Reported by the DOCCS annual releases and discharges from incarceration report.",
                                        x="Year",
                                        y="Individuals released (number)",
                                        color="Age group") + theme_nycc()
```

```{r, include=FALSE}
# ----- AGE OF PEOPLE RELEASED FROM DOC FACILITIES OVER TIME -----
# --- OF AGING INDIVIDUALS ---
# These were individuals who were released to the community for the first time on their current sentence due to release by the Board of Parole, release due to reaching their approved conditional release date (including maximum expiration with post-release supervision), or release based on reaching maximum expiration of sentence.
p <- ggplot(data=year_age_fr) + 
  geom_line(aes(x=year, y=age50_59/total_50_over, colour="50-59")) +
  geom_line(aes(x=year, y=age60_64/total_50_over, colour="60-64")) +
  geom_line(aes(x=year, y=age65_69/total_50_over, colour="65-69")) +
  geom_line(aes(x=year, y=age_70over/total_50_over, colour="70+")) +
  scale_x_continuous(n.breaks=9) + 
  scale_y_continuous(labels=scales::percent) + labs(title="NYS First Releases Ages 50+ Breakdown (2011-2020)", 
                                        subtitle="Reported by the DOCCS annual releases and discharges from incarceration report.",
                                        x="Year",
                                        y="Individuals released (proportion)",
                                        color="Age group") + 
  theme_nycc()
```

```{r}
#png(filename="firstreleases_age_num_d.png", width=600, height=400)
p <- ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_50_over, colour="all ages 50+"),
            size=1, linetype="dashed") +
  geom_line(aes(x=year, y=(age17+age18+age19+age20+age21), colour="21 and under")) +
  geom_line(aes(x=year, y=(age22_24+age25_29), colour="22-29")) +
  geom_line(aes(x=year, y=(age30_34+age35_39), colour="30-39")) +
  geom_line(aes(x=year, y=(age40_49), colour="40-49")) +
  scale_x_continuous(n.breaks=9) + 
  labs(title="NYS First Releases (2011-2020)", 
                                        subtitle="Reported by the DOCCS annual releases and discharges from incarceration report.",
                                        x="Year",
                                        y="Individuals released (number)",
                                        color="Age group by decades") + 
  theme_nycc() + scale_color_nycc()
p
ggsave(p, filename = "../visuals/firstreleases_age_num_d.png", width = 8, height = 5)
#dev.off()
```

```{r}
# ----- AGE OF PEOPLE RELEASED FROM DOC FACILITIES OVER TIME -----
# ----- BY DECADE
# These were individuals who were released to the community for the first time on their current sentence due to release by the Board of Parole, release due to reaching their approved conditional release date (including maximum expiration with post-release supervision), or release based on reaching maximum expiration of sentence.

#png(filename="firstreleases_age_prop_d.png", width=600, height=400)

p<- 
ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_50_over/total_released, colour="50 & Over"),
            size=1, linetype="dashed") +
  geom_line(aes(x=year, y=(age17+age18+age19+age20+age21)/total_released, colour="21 & under")) +
  geom_line(aes(x=year, y=(age22_24+age25_29)/total_released, colour="22-29")) +
  geom_line(aes(x=year, y=(age30_34+age35_39)/total_released, colour="30-39")) +
  geom_line(aes(x=year, y=(age40_49)/total_released, colour="40-49")) +
  scale_x_continuous(n.breaks=9) + scale_y_continuous(labels=scales::percent) +
  labs(title="NYS First Releases (2011-2020)", 
                                        subtitle="Reported by the DOCCS Annual Releases and Discharges From Incarceration Report.",
                                        x="Year",
                                        y="Percent of Individuals Released ",
                                        color="Age Group") + 
  theme_nycc() + scale_color_nycc()

p

ggsave(p, filename = "../visuals/firstreleases_age_prop_d.png", width = 8, height = 5)

#dev.off()
```

```{r}
# ----- AGE OF PEOPLE RELEASED FROM DOC FACILITIES OVER TIME -----
# These were individuals who were released to the community for the first time on their current sentence due to release by the Board of Parole, release due to reaching their approved conditional release date (including maximum expiration with post-release supervision), or release based on reaching maximum expiration of sentence.
png(filename="firstreleases_age_num.png", width=600, height=400)
a <- ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_50_over, colour="all ages 50+")) +
  geom_line(aes(x=year, y=(age17+age18+age19+age20+age21), colour="21 and under")) +
  geom_line(aes(x=year, y=(age22_24), colour="22-24")) +
  geom_line(aes(x=year, y=(age25_29), colour="25-29")) +
  geom_line(aes(x=year, y=(age30_34), colour="30-34")) +
  geom_line(aes(x=year, y=(age35_39), colour="35-39")) +
  geom_line(aes(x=year, y=(age40_49), colour="40-49")) +
  scale_x_continuous(n.breaks=9) + labs(title="NYS First Releases (2011-2020)", 
                                        subtitle="Reported by the DOCCS annual releases and discharges from incarceration report.",
                                        x="Year",
                                        y="Individuals released (number)",
                                        color="Age group") + theme_nycc()
dev.off()
```

```{r}
# ----- AGE OF PEOPLE RELEASED FROM DOC FACILITIES OVER TIME -----
# These were individuals who were released to the community for the first time on their current sentence due to release by the Board of Parole, release due to reaching their approved conditional release date (including maximum expiration with post-release supervision), or release based on reaching maximum expiration of sentence.
png(filename="firstreleases_age_prop.png", width=600, height=400)
b <- ggplot(data=year_age_fr) +
  geom_line(aes(x=year, y=total_50_over/total_released, colour="all ages 50+")) +
  geom_line(aes(x=year, y=(age17+age18+age19+age20+age21)/total_released, colour="21 and under")) +
  geom_line(aes(x=year, y=(age22_24)/total_released, colour="22-24")) +
  geom_line(aes(x=year, y=(age25_29)/total_released, colour="25-29")) +
  geom_line(aes(x=year, y=(age30_34)/total_released, colour="30-34")) +
  geom_line(aes(x=year, y=(age35_39)/total_released, colour="35-39")) +
  geom_line(aes(x=year, y=(age40_49)/total_released, colour="40-49")) +
  scale_x_continuous(n.breaks=9) + scale_y_continuous(labels=scales::percent) +
  labs(title="NYS First Releases (2011-2020)", 
                                        subtitle="Reported by the DOCCS annual releases and discharges from incarceration report.",
                                        x="Year",
                                        y="Individuals released (proportion)",
                                        color="Age group") +
  theme_nycc()
dev.off()
```

```{r, include=FALSE}
levels(year_age_tr_return$cohort)
year_age_tr_return$cohort <- factor(year_age_tr_return$cohort, levels=c("release","total_return","parole_v","new_comm"))
levels(year_age_tr_return$cohort)
year_age_tr_return <- year_age_tr_return %>%
  mutate(cohort = recode(cohort,
                                       "release" = "total released",
                                       "total_return" = "returned",
                                       "parole_v" = "parole violation",
                                       "new_comm"="new committment"))
```

```{r}
#png(filename="followup_num.png", width=600, height=400)
c <- ggplot(data=year_age_tr_return) +
  geom_line(aes(x=year,y=num_50_over,col=cohort)) +
  scale_x_continuous(n.breaks=10) + 
  labs(title="Three-Year Post-Release Follow Up (Ages 50+, 2008-2018)",
       subtitle= "Reported by the DOCCS Annual Inmate Releases Report.",
       x="Year Released",
       y="Number of Individuals Released", color="Cohort") +
 theme_nycc() + scale_color_nycc()
c
ggsave(c, filename = "../visuals/followup_num.png", width = 8, height = 5)
#dev.off()
```

```{r}
# a2 <- ggplot_build(a)$data
# b2 <- ggplot_build(b)$data
# c2 <- ggplot_build(c)$data
```

```{r}
# write.csv(a2, "frplot_num.csv")
# write.csv(b2, "frplot_prop.csv")
# write.csv(c2, "3yrpostplot.csv")
```

```{r}
state_app <- read.csv("../data/input/raw/state_approxcommits.csv")
head(state_app)
```

```{r}
# num of fr aged 50+ returning to nyc (approx)
ggplot(data=state_app) +
  geom_line(aes(x=year, y=num_nycfr50)) + scale_x_continuous(n.breaks=9) +
  theme_nycc()

# prop of fr aged 50+ returning to nyc (approx) out of total fr
ggplot(data=state_app) +
  geom_line(aes(x=year, y=num_nycfr50/total_fr)) + scale_x_continuous(n.breaks=9) + scale_y_continuous(labels=scales::percent) + 
  labs(x="Year", y="Individuals committed to NYC (proportion)") +
  theme_nycc()

```
